# Generated by Django 3.2.6 on 2024-07-02 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_matrimoniale', models.CharField(choices=[('Célibataire', 'Célibataire'), ('Mariée', 'Marié'), ('Separée', 'Separé'), ('Divorcée', 'Divorcé'), ('Veufve', 'Veuf')], max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('nom_prenom', models.CharField(max_length=100)),
                ('id_agent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('age', models.PositiveIntegerField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('anciennete_agence', models.PositiveIntegerField(help_text='En années')),
                ('montant_solicite', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duree_pret_souhaitee', models.PositiveIntegerField(help_text='En mois')),
                ('nombre_echeance', models.PositiveIntegerField()),
                ('taux_interet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('periodicite_remboursement', models.CharField(choices=[('Mensuelle', 'Mensuelle'), ('Bimensuelle', 'Bimensuelle'), ('Trimestrielle', 'Trimestrielle'), ('Semestrielle', 'Semestrielle'), ('Annuelle', 'Annuelle')], max_length=20)),
                ('secteur_activite', models.CharField(max_length=100)),
                ('sous_secteur_activite', models.CharField(max_length=100)),
                ('nombre_mois_cotisation', models.PositiveIntegerField()),
                ('statut', models.BooleanField()),
                ('nbr_credits_octroyes', models.PositiveIntegerField()),
                ('nbr_credits_rembourses', models.PositiveIntegerField()),
                ('montant_credits_accorde', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
