# Generated by Django 3.2.6 on 2024-07-02 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_analyse',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
