# Generated by Django 3.2.6 on 2024-07-03 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0002_demande_date_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='date_rembouse',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='demande',
            name='statut_traite',
            field=models.CharField(choices=[('rejeté', 'Rejeté'), ('accept', 'Accepté'), ('en attente', 'En attente')], default='en attente', max_length=10),
        ),
        migrations.AlterField(
            model_name='demande',
            name='sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10),
        ),
    ]
