# Generated by Django 3.2.6 on 2024-07-03 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demande', '0003_auto_20240703_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='but_demande',
            field=models.CharField(default='Neant', max_length=1000),
        ),
    ]
